baseurl = "jamiedumont.netlify.com"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Jamie Dumont"
title = "Jamie Dumont | Web Designer & Developer"
pluralizelisttitles = false
pygmentsuseclasses = true
PygmentsCodeFences = true

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
author = "Jamie Dumont"
cachebuster = true
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Example blog"
logofile = "js_logo.svg"
faviconfile = "icon.svg"
lang = "en"
github = "https://github.com/jamiedumont"
email = "jamiedumont@icloud.com"
linkedin = "example"
twitter = "@jamiedumont"