baseurl = "http://advisor-henry-18063.netlify.com"
theme = "custom"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Jamie Dumont"
title = "Tactically Creative"
pluralizelisttitles = false

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
author = "Jamie Dumont"
cachebuster = true
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Example blog"
logofile = "img/logo.svg"
faviconfile = "img/icon.svg"
lang = "en"
github = "https://github.com/jamiedumont"
email = "jamie@tactically-creative.co.uk"
linkedin = "example"
twitter = "@jamiedumont"
